require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '94706042889',
    MODE: (process.env.MODE || 'public').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'HASHAN-MD',
    ANTICALL: process.env.ANTICALL || 'off',
    ADM: process.env.ANTIDELETE || 'on',
    AR: process.env.AUTO_REACTION || 'off',

    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0ZrelBaQndUS21VYko0SHpzU0FJa3NJdzdqN2JnZWtXSGQwUWhRakJWdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS2IwTUtiRVZMZDdzUDM4MTIrNkZORThnQzBHK0VuMzdldERRa29yOElXbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ3QThoQ1FoM3V5QUpHVTJYQ1pFRUI3T0ZtZHRNa05rSTFueXdsZTZBblZFPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHQnNvelBpU05qb0lFZWwwODlCUDRtYjRHVmtHQTZ5VGxoU2tVV2hZeUFRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlFFS3M5cnhDdHZ1Nm9uaDVQbmh3WG04TFlZMlBRSWF3MnMyNUxvT0NnbTg9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IklRcU1Nbys3U044RVRPTGVmaTg4OGdVZ2FBRWZkaUZBWGdQVm1MTnZpUXc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYU51Y1h2bEpiNmczcmU3MHRJUk9kTmduTEpDQjlQcThEc3JBUURGZ3pVVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS1lJNmM5N3loMDFyaVZnRHExcW1Oa3NQK0JWU1lPOUpYUlFtQXFwa2YyUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlRWdkE2bkR6U1dDWkRCSW9nU2ZSc0ZncXBBOHhJSjNnN1FCZWhLb3Yzbmh0R0NaL0hTdzFKdUxHT2g0OXhreU9RV3NkYlFxVVF3WGJ5Mkl0djBEYWpRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NzcsImFkdlNlY3JldEtleSI6InRwTXo3Z1VGSFQ3RHNuQjNBSCtoNUk0cERKcnpid1lJRmZQYVN5aEtyN2s9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NzgyNDE5ODNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNkNGQzkzRjU5QTY0MzJEN0E5NjUzNURDOUZBNTRBOUQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NTA2NzAyOX0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NzgyNDE5ODNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMUU4Mzk0QjUxNkE4MEY1QjgxNEI0M0I4REVGQzFBQTMifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NTA2NzAyOX0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTQ3NzgyNDE5ODNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMkRBQjkyRkU1MzAxRTRGNzc5QTg0N0RDOEQ5MkFCRDkifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1NTA2NzAzNn1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiRjJNR1dLM0siLCJtZSI6eyJpZCI6Ijk0Nzc4MjQxOTgzOjhAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiQm90IiwibGlkIjoiNTIwNjg0NTg5NTQ3NjU6OEBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ08zWHdmc0ZFSVBsOE1RR0dBY2dBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImRydnc4c2M3TDNIQTBrNmM0YUNnbTFURlBYR0ZFMlo0SzlDT1ZHMk9UMjg9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjZKbUpjYVJueUZzZDhkOXQ4aE9WS1BxWWtKbTlGS0RpMzllZDRqdVJDbjV3THpRSlduTzRMejM1U2JhMjJrb29LelRwZU1aMDlqaFZYdGZNdzZpakJRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJDc0tYeVd1akZPdCs3ZzN6ZGJtbVE2WWtkWUtid3dSMDM0ZTZmdUdIL2NoRFB0T0p1WGoyU2F0ZUlQaGswRTVsb2pkZElIRUVuNUd0VVdmQmZOVWRoQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6Ijk0Nzc4MjQxOTgzOjhAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWGE3OFBMSE95OXh3TkpPbk9HZ29KdFV4VDF4aFJObWVDdlFqbFJ0ams5diJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FnSUVnPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU1MDY3MDI1LCJsYXN0UHJvcEhhc2giOiIxSzRoSDQiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUtIaCJ9',
    timezone: 'Africa/Nairobi',

    USER_LID: process.env.YOUR_LID, 

    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
